---
name: Ansible Molecule with collection support
description: Run Ansible Molecule with collection support
author: Thomas Grimonet <tgrimonet@arista.com>

branding:
  icon: upload
  color: green

inputs:
  molecule_parentdir:
    description: Relative path where your molecule folder is.
    required: true
    default: '.'

  molecule_options:
    description: |
      Options:
        --debug / --no-debug    Enable or disable debug mode. Default is disabled.
        -c, --base-config TEXT  Path to a base config.  If provided Molecule will
                                load this config first, and deep merge each
                                scenario's molecule.yml on top.
                                (/home/gofrolist/.config/molecule/config.yml)
        -e, --env-file TEXT     The file to read variables from when rendering
                                molecule.yml. (.env.yml)
        --version               Show the version and exit.
        --help                  Show this message and exit.
    required: false

  molecule_command:
    description: |
      Commands:
        check        Use the provisioner to perform a Dry-Run...
        cleanup      Use the provisioner to cleanup any changes...
        converge     Use the provisioner to configure instances...
        create       Use the provisioner to start the instances.
        dependency   Manage the role's dependencies.
        destroy      Use the provisioner to destroy the instances.
        idempotence  Use the provisioner to configure the...
        init         Initialize a new role or scenario.
        lint         Lint the role.
        list         Lists status of instances.
        login        Log in to one instance.
        matrix       List matrix of steps used to test instances.
        prepare      Use the provisioner to prepare the instances...
        side-effect  Use the provisioner to perform side-effects...
        syntax       Use the provisioner to syntax check the role.
        test         Test (lint, cleanup, destroy, dependency,...
        verify       Run automated tests against instances.
    required: true
    default: 'test'

  molecule_args:
    description: |
      Arguments:
        --scenario-name foo  Targeting a specific scenario.
        --driver-name foo    Targeting a specific driver.
        --all                Target all scenarios.
        --destroy=always     Always destroy instances at the conclusion of a Molecule run.
    required: false

  pip_file:
    description: |
      Relative path from `${GITHUB_REPOSITORY}` to install
      any requirements prior to run molecule
    required: false
    default: ''

  check_git:
    description: |
      Check git status after molecule execution.
      Help to track unexpected changes between 2 commits.
    required: false
    default: 'false'

  check_git_enforced:
    description: |
      If set to to true, then exit code is based on git status.
    required: false
    default: 'false'

runs:
  using: docker
  image: avdteam/action-molecule:v1.0